
package WebServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankWebService", targetNamespace = "http://BankServices", wsdlLocation = "file:///Users/Aymeric/IdeaProjects/6231-03-WebService/Server/BankServer/src/BankServices/BankWebService.wsdl")
public class BankWebService_Service
    extends Service
{

    private final static URL BANKWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKWEBSERVICE_EXCEPTION;
    private final static QName BANKWEBSERVICE_QNAME = new QName("http://BankServices", "BankWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///Users/Aymeric/IdeaProjects/6231-03-WebService/Server/BankServer/src/BankServices/BankWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKWEBSERVICE_WSDL_LOCATION = url;
        BANKWEBSERVICE_EXCEPTION = e;
    }

    public BankWebService_Service() {
        super(__getWsdlLocation(), BANKWEBSERVICE_QNAME);
    }

    public BankWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKWEBSERVICE_QNAME, features);
    }

    public BankWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, BANKWEBSERVICE_QNAME);
    }

    public BankWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKWEBSERVICE_QNAME, features);
    }

    public BankWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankWebService
     */
    @WebEndpoint(name = "BankWebService")
    public BankWebService getBankWebService(Data.Bank bank) {
        return super.getPort(new QName("http://BankServices", bank.name()), BankWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankWebService
     */
    @WebEndpoint(name = "BankWebService")
    public BankWebService getBankWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://BankServices", "BankWebService"), BankWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKWEBSERVICE_EXCEPTION!= null) {
            throw BANKWEBSERVICE_EXCEPTION;
        }
        return BANKWEBSERVICE_WSDL_LOCATION;
    }

}
